package migrate

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/pelletier/go-toml/v2"

	"github.com/chmouel/rc/internal/config"
)

// Options configures a migration run.
type Options struct {
	LegacyRoot   string
	OutputRoot   string
	RCAssetsRoot string
	RepoBase     string
}

// Result summarizes the conversion of one host profile.
type Result struct {
	Profile    string
	OutputFile string
	Links      int
	Bins       int
	Repos      int
	Warnings   []string
}

// overlayOut is the TOML overlay produced for a host profile.
type overlayOut struct {
	Version      int           `toml:"version"`
	Links        []config.Link `toml:"links,omitempty"`
	Bins         []config.Bin  `toml:"bins,omitempty"`
	Repositories []repoOut     `toml:"repositories,omitempty"`
}

// repoOut mirrors config.Repository but stores Hooks as an omittable pointer so
// repositories without hooks do not emit an empty "[repositories.hooks]" table.
type repoOut struct {
	Path  string        `toml:"path"`
	Hooks *config.Hooks `toml:"hooks,omitempty"`
}

func toRepoOut(r config.Repository) repoOut {
	out := repoOut{Path: r.Path}
	if r.Hooks.PostUpdate != nil || r.Hooks.Always != nil {
		h := r.Hooks
		out.Hooks = &h
	}
	return out
}

// Migrate converts every host profile under LegacyRoot into a TOML overlay
// under OutputRoot.
func Migrate(opts Options) ([]Result, error) {
	entries, err := os.ReadDir(opts.LegacyRoot)
	if err != nil {
		return nil, fmt.Errorf("reading legacy root: %w", err)
	}

	var results []Result
	for _, e := range entries {
		if !e.IsDir() || (len(e.Name()) > 0 && e.Name()[0] == '.') {
			continue
		}
		profileDir := filepath.Join(opts.LegacyRoot, e.Name())
		overlay, warnings := Convert(profileDir, opts)
		if len(overlay.Links) == 0 && len(overlay.Bins) == 0 && len(overlay.Repositories) == 0 {
			continue
		}

		data, err := Render(overlay, warnings)
		if err != nil {
			return nil, fmt.Errorf("rendering %s: %w", e.Name(), err)
		}
		outDir := filepath.Join(opts.OutputRoot, e.Name())
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return nil, err
		}
		outFile := filepath.Join(outDir, "rc.toml")
		if err := os.WriteFile(outFile, data, 0o644); err != nil {
			return nil, err
		}
		results = append(results, Result{
			Profile:    e.Name(),
			OutputFile: outFile,
			Links:      len(overlay.Links),
			Bins:       len(overlay.Bins),
			Repos:      len(overlay.Repositories),
			Warnings:   warnings,
		})
	}

	sort.Slice(results, func(i, j int) bool { return results[i].Profile < results[j].Profile })
	return results, nil
}

// Convert reads the legacy files in a profile directory and returns the overlay.
func Convert(profileDir string, opts Options) (overlayOut, []string) {
	overlay := overlayOut{Version: 1}
	var warnings []string

	if content, ok := readFile(filepath.Join(profileDir, "rc")); ok {
		overlay.Links = append(overlay.Links, parseRC(content, opts.RCAssetsRoot)...)
	}
	if content, ok := readFile(filepath.Join(profileDir, "chmouzies")); ok {
		overlay.Bins = append(overlay.Bins, parseBinList(content, "chmouzies")...)
	}
	if content, ok := readFile(filepath.Join(profileDir, "repobins")); ok {
		overlay.Bins = append(overlay.Bins, parseBinList(content, "repo_base")...)
	}
	if content, ok := readFile(filepath.Join(profileDir, "extra-dirs")); ok {
		for _, r := range parseExtraDirs(content) {
			overlay.Repositories = append(overlay.Repositories, toRepoOut(r))
		}
	}

	var w []string
	overlay.Links, w = dedupeLinks(overlay.Links)
	warnings = append(warnings, w...)
	overlay.Bins, w = dedupeBins(overlay.Bins)
	warnings = append(warnings, w...)
	return overlay, warnings
}

// Render marshals an overlay to TOML with a generated-file header and warning
// comments.
func Render(overlay overlayOut, warnings []string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by `rc migrate`. Review before use.\n")
	for _, w := range warnings {
		buf.WriteString("# WARNING: " + w + "\n")
	}
	buf.WriteString("\n")

	body, err := toml.Marshal(overlay)
	if err != nil {
		return nil, err
	}
	buf.Write(body)
	return buf.Bytes(), nil
}

func readFile(path string) (string, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	return string(data), true
}

// dedupeLinks drops links that are byte-identical to an earlier entry and warns
// about distinct sources that collide on the same target. Legacy configs may
// contain accidental duplicates; the runtime rejects duplicate targets within a
// layer, so they must be resolved at migration time.
func dedupeLinks(links []config.Link) ([]config.Link, []string) {
	seen := make(map[string]config.Link, len(links))
	out := make([]config.Link, 0, len(links))
	var warnings []string
	for _, l := range links {
		if prev, ok := seen[l.Target]; ok {
			if prev != l {
				warnings = append(warnings, "dropped conflicting link for target "+l.Target+" (kept source "+prev.Source+", discarded "+l.Source+")")
			}
			continue
		}
		seen[l.Target] = l
		out = append(out, l)
	}
	return out, warnings
}

// dedupeBins applies the same identical-drop / conflict-warn policy to bins.
func dedupeBins(bins []config.Bin) ([]config.Bin, []string) {
	seen := make(map[string]config.Bin, len(bins))
	out := make([]config.Bin, 0, len(bins))
	var warnings []string
	for _, b := range bins {
		if prev, ok := seen[b.Target]; ok {
			if prev != b {
				warnings = append(warnings, "dropped conflicting bin for target "+b.Target+" (kept source "+prev.Source+", discarded "+b.Source+")")
			}
			continue
		}
		seen[b.Target] = b
		out = append(out, b)
	}
	return out, warnings
}
